### ISSUE TITLE
Render a component with FlowLayout

### ISSUE THREAD

**Issue by PhilippSpo** [meteorhacks/flow-components#15]
Is it possible to render a component using Flow Layout?
Right now i am rendering a 'traditional' template that renders the flow component like you say in the readme `{{> render component="userDetails"}}`
Doing something like

    FlowLayout.render('layout', {
		top: "userDetailsToolbar",
		main: "userDetails",
		aside: 'menu'
	});

where userDetails is a flow-component doesn't work sadly.

**Comment by arunoda** [comment]
I need to a sample. Without that it's hard to say.

**Comment by PhilippSpo** [comment]
userDetails-view.html:

    <template name="userDetails">
    	{{#with state$user}}
    		<ul class="collection with-header">
    			<li class="collection-header"><h4>Philipp Sporrer</h4></li>
    			<li class="collection-item"><div>{{_id}}</div></li>
    		</ul>
    	{{/with}}
    </template>
    
userDetails.js:

    var userDetails = FlowComponents.define('userDetails', function() {
    });
    
    userDetails.state.user = function() {
    	return Meteor.users.findOne({});
    };
    
layout.html

    <template name="layout">
    	
	    {{> Template.dynamic template=top}}
    	    						
		{{> Template.dynamic template=aside}}
    	
    		
    	<main>
    		<div class="row">
    			{{> Template.dynamic template=main}}
    		</div>
    	</main>
    </template>
    
router.js

    FlowRouter.route('/users/:userId', {
    	subscriptions: function(params) {
    		this.register('users', Meteor.subscribe('user', params.userId));
    	},
    	action: function(params) {
    		FlowLayout.render('layout', {
    			top: "userDetailToolbar",
    			// 'userDetails' is not rendered (no error) -> 'userDetailsRenderer' is working as described below
    			main: "userDetails",
    			aside: 'menu'
    		});
    	}
    });
    
that's basically my code.
To get this working I have another template that renders the userDetails template:

    <template name="userDetailsRenderer">
    	{{> render component="userDetails"}}
    </template>

**Comment by arunoda** [comment]
In the main layout, you can have something like this:

~~~html
<template name="layout">
    <!-- some irrelevant code here -->
    {{> Template.dynamic template=top}}
    <!-- some irrelevant code here -->                          
    {{> Template.dynamic template=aside}}
    <!-- some irrelevant code here -->

    <main>
        <div class="row">
            {{> render component=main}}
        </div>
    </main>
</template>
~~~

**Comment by PhilippSpo** [comment]
ok that was pretty simple thank you :)
Did I miss that in the documentation somewhere ?
One more question: Should I do subscriptions in the FlowRouter or in the components?

**Comment by arunoda** [comment]
It's upto you. If you need to find subscriptions into a route, do it in the router.

**Comment by PhilippSpo** [comment]
ok. thanks again
