### ISSUE TITLE
[Question] What is right approach?

### ISSUE THREAD

**Issue by delgermurun** [meteorhacks/flow-components#17]
I'm about to convert templates into components. I've no prior experience on component based architecture. But I researched and I think I've basic understanding.

I wonder what is right approach for meteor. How do you use it? Is everything component, even simple templates? Or do you mix templates and components?

I think, it would very useful if there is an complete example project.

Thank you.

/cc @arunoda @christianvoigt

**Comment by arunoda** [comment]
Hi,

You don't need to do that for every templates.
Anyway, we do it for all.

Unfortunately, we don't have a sample open source project.

**Comment by delgermurun** [comment]
@arunoda Thanks.
