### ISSUE TITLE
How to access parent component?

### ISSUE THREAD

**Issue by delgermurun** [meteorhacks/flow-components#18]
Can I access parent component?

I need to call parent component's action or change state.

**Comment by arunoda** [comment]
We don't support accessing the parent comp. from child.
Instead, you can pass an action to the child component like this:
https://github.com/meteorhacks/flow-components#via-props-aka-action-passing

That's the way we recommend to do.

**Comment by delgermurun** [comment]
Cool. Work like a charm.

Thanks.
