### ISSUE TITLE
Bug on switching between component based layout and template based layout

### ISSUE THREAD

**Issue by delgermurun** [meteorhacks/flow-components#19]
I have two layout one with component and other with template. There is two bugs.

- When switch from page with template based layout to page with component based layout, flow components throws error: `Exception from Tracker recompute function: FlowComponent needs 'component' parameter`
- When vice versa (component => template), it doesn't render peices, only renders layout.

Here is reproduction repo (on master branch): https://github.com/delgermurun/flow-demo/tree/master

**Comment by arunoda** [comment]
Hey I think this is related to https://github.com/meteorhacks/flow-layout/issues/1
I fixed it. Can you please try this with the new flow-layout version?

**Comment by delgermurun** [comment]
@arunoda works like a charm. Thanks a lot.
