### ISSUE TITLE
Uncaught Error: Must be attached

### ISSUE THREAD

**Issue by delgermurun** [meteorhacks/flow-components#20]
I render components which depends on previous components. When select box value change, remove all components after it's component and rerender one component after it. I use client side collection for it.

It works. But when remove components, blaze throws error. `Must be attached` from https://github.com/meteor/meteor/blob/devel/packages/blaze/domrange.js#L337

Here is reproduction repo (on dynamic-render branch): https://github.com/delgermurun/flow-demo/tree/dynamic-render

**Comment by delgermurun** [comment]
@arunoda 

I tested it using template (https://github.com/delgermurun/flow-demo/tree/with-template). It also throws error.

So It isn't `flow-components`'s issue.

Anyway, I'd appreciate if you take a look and pointing what  I'm doing wrong (or meteor :P) :).

Thanks.

**Comment by pcuci** [comment]
Looks like a known issue with Meteor: https://github.com/meteor/meteor/issues/2981
