### ISSUE TITLE
Passing a function to component

### ISSUE THREAD

**Issue by npvn** [meteorhacks/flow-components#22]
I'm trying to create a button component. This button accepts a function as prop. This function will be executed when the button is clicked.

My main template:

```html
<template name='App'>
    {{> render buttonConfig}}
</template>
```
```javascript
Template.App.helpers({
    buttonConfig: function() {
        return {
            component: 'button',
            label: 'Demo Button', 
            onClick: function() { console.log('The button is clicked'); }
        };
    }
});
```

My button component:

```html
<template name='button'>
    <button>{{state$label}}</button>
</template>
```
```javascript
var component = FlowComponents.define('button', function(props) {
    this.set('label', props.label); 
    this.set('onClick', props.onClick);
});

component.action.onClick = function() {
    onClickFunction = this.get('onClick'); // undefined 
    onClickFunction();
};

Template.button.events({
    'click': function() {
        FlowComponents.callAction('onClick');
    }
});

```

The problem seems to be that a component's state cannot contain a function, so `this.get('onClick')` always returns `undefined`. If so, is there a better way to implement this button component?

**Comment by arunoda** [comment]
We do this via action passing: https://github.com/meteorhacks/flow-components#via-props-aka-action-passing

That means, button accept a prop called onClick and we pass an action of the parent component into that.

Like this:

~~~html
{{>render component="button" onClick=action$doSomething}}
~~~

I hope, this is what you looked for.

**Comment by npvn** [comment]
In my case I don't have a parent component - The button component is used directly on my main template (`App`).

Is there a way to pass a function from main template to the button component (please review my example above)?

I can certainly refactor the main template and turn it into a component, but I think that's not an elegant solution.

**Comment by arunoda** [comment]
Then there is a hacky way to do that with a template helper.

~~~
Template.foo.helpers({
  doAction: function() {
    return function() {
      console.log("Button Clicked");
    }
  }
});

{{> render component="button" onClick=doAction}}
~~~

**Comment by npvn** [comment]
I realized passing a function like this is not a nice solution, either. Maybe I should better rethink the way I structure my components.

Thanks Arunoda.

**Comment by arunoda** [comment]
Got it.
