### ISSUE TITLE
Content block is not working

### ISSUE THREAD

**Issue by npvn** [meteorhacks/flow-components#23]
I'm trying to create a component with content block, exactly similar to the example at
https://github.com/meteorhacks/flow-components#content-blocks

However, the text `[object Object]` is shown instead of the expected content.

**Comment by pward123** [comment]
+1

**Comment by arunoda** [comment]
Actually, it was a typo:
You need to render it as a template.
See:

~~~html
<template name="loading">
  {{#if state$loaded}}
    {{> flowContentBlock }}
  {{else}}
    {{> flowElseBlock }}
  {{/if}}
</template>
~~~

**Comment by npvn** [comment]
:+1:
