### ISSUE TITLE
Created callbacks in mixins not working

### ISSUE THREAD

**Issue by rclai** [meteorhacks/flow-components#24]
On your example [here](https://github.com/meteorhacks/flow-components#extending-components-with-mixins), when I tested that mixin on one of my components:

```js
var component = FlowComponents.define('notes', function (props) {
  this.subscribe('notes');
});

component.extend(ComponentSubs);
```

It errored because `this._subs` is `undefined`. I debugged and saw that the `created` callback never runs, and therefore the `_subs` property is never created. Is this because of Meteor `1.0.4`?

**Comment by rclai** [comment]
After digging around, [this line of code](https://github.com/meteorhacks/flow-components/blob/master/lib/client/api.js#L55) is what is causing the issues. Because this callback is added at the end of the `created` array, and you execute the `created` callbacks in order, `_subs` is not defined because it's the second callback. So you either have to execute the callbacks backwards or `unshift` callbacks.

**Comment by arunoda** [comment]
Above PR looks good. But, we need to push callbacks to the array.
So, with that someone can have a mixin dependancy chain.
But if we use unshift, it will break. 

Best solution is to separate main created callback from the rest and call if after mixins done their job.
I did it with: https://github.com/meteorhacks/flow-components/commit/6672928cdcd906fa9f1829ce2fe5bcfd636dcfc5

**Comment by arunoda** [comment]
Can you check it with your app.

**Comment by rclai** [comment]
That's a better idea. Thanks. I will test this tonight.

**Comment by rclai** [comment]
Works. Thanks!
