### ISSUE TITLE
How would you set props in component/template/markup?

### ISSUE THREAD

**Issue by rolfnl** [meteorhacks/flow-components#27]
I wonder what the approach is to use props in the components markup (in the template) instead of state variables?

**Comment by rclai** [comment]
By using props you allow your components to set dynamic states based on what is passed in, most likely from a parent component. For example, a parent component can pass a property to a child component in order for it to have a specific state. This child component can then be reused somewhere else.

```js
var todosComponent = FlowComponents.define('todos', function (props) {
  this.set('todos', Todos.find({}));
  // @arunoda, is it better for the 'todos' state to be in a setFn, or is this fine?
});

var todoComponent = FlowComponents.define('todo', function (props) {
    this.set('todo', props.todo);
});
```

```html
<template name="todos">
  <div class="todos">
    {{#each state$todos}}
      {{> render component="todo" todo=this}}
    {{/each}}
  </div>
</template>

<template name="todo">
  {{#with state$todo}}
    <div class="todo">
      {{title}} - {{description}}
    </div>
  {{/with}}
</template>
```

**Comment by arunoda** [comment]
Since todo is a cursor set is fine.

On the other hand, @Rolf you can access properties from the template via
prop helper. For an example, let's say you have a prop called name. Then
you can get it inside the template with:

{{prop "name" }}

**Comment by rolfnl** [comment]
@rclai yes those are states/reactive vars/props.. I meant the non reactive ones.. the (basic) props ;)

@arunoda ah, thanks I see.. and I also see it now here https://github.com/meteorhacks/flow-components/blob/master/lib/client/lookup.js#L14 .. cheers!
