### ISSUE TITLE
Flow components + subscriptions manager

### ISSUE THREAD

**Issue by bitomule** [meteorhacks/flow-components#44]
I've a template level subscription inside a template autorun. If I use Meteor subscribe method it clears client data before fetching new one from server publication and using subsmanager subscribe just doesn't even run the publication so client data never appears.

I've this autorun inside my component:

```
this.autorun(function(){
        subman.subscribe("samplepub_" + that.type,that.item,that.get("searchFilter"),that.get("usersFilter"),that.get("countLimit"));
    })
```

Any idea on where's the problem? Why subscription manager doesn't work inside a component?

**Comment by arunoda** [comment]
Component Level subs do work. As well as the subs manager.
This is how we do it: https://github.com/meteorhacks/flow-components#extending-components-with-mixins

**Comment by bitomule** [comment]
Thanks. Finally found that issue was sub manager cache limit.

**Comment by arunoda** [comment]
Ah ha. I guessed that.  I posted to check that on a similar issue on the subsManager repo.
